spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n/message
#  datasource:
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/huadou?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    type: com.alibaba.druid.pool.DruidDataSource